#!/usr/bin/env bash

# Update package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/# listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default

# Restart nginx
sudo /etc/init.d/nginx restart

# Create index.html file with "Hello World!" message
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
