#!/usr/bin/bash
# Creates an RSA key pair.
# Name of the created private key is school
# Number of bits in the key tobe created is 4096.
# The created key is protected by passphrase betty.
ssh-keygen -t rsa -b 4096 -P betty -f school
