#!/usr/bin/bash
# Script that creates an RSA key pair.

# Set the name and number of bits for the private key
KEY_NAME="school"
KEY_BITS=4096

# Generate the key pair with a passphrase
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N "betty"

# Display the fingerprint and randomart image of the key
ssh-keygen -lvf $KEY_NAME
